In [116]:
import pandas as pd
boxoffices = pd.read_html('https://movie.datamotion.co.kr/Boxoffice')
df_boxoffice = boxoffices[1]

In [117]:
df_boxoffice

,0,1,2,3,4,5
0,순위,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
1,1,아바타 (2009),"$2,847,246,203","$760,507,625",26.71%,"$237,000,000"
2,2,어벤저스: 엔드게임 (2019),"$2,797,501,328","$858,373,000",30.68%,"$356,000,000"
3,3,타이타닉 (1997),"$2,201,647,264","$659,363,944",29.95%,"$200,000,000"
4,4,스타 워즈: 깨어난 포스 (2015),"$2,068,223,624","$936,662,225",45.29%,"$245,000,000"
...,...,...,...,...,...,...
196,196,월드워 Z (2013),"$540,007,876","$202,359,711",37.47%,"$190,000,000"
197,197,메리다와 마법의 숲 (2012),"$538,983,207","$237,283,207",44.02%,"$185,000,000"
198,198,"심슨가족, 더 무비 (2007)","$536,414,270","$183,135,014",34.14%,"$75,000,000"
199,199,레버넌트: 죽음에서 돌아온 자 (2015),"$532,950,503","$183,637,894",34.46%,"$135,000,000"
200,200,메가로돈 (2018),"$530,243,742","$145,443,742",27.43%,"$130,000,000"

인덱스를 순위로

In [118]:
df_boxoffice.iloc[0]

0          순위
1          영화
2    세계 흥행 수익
3    북미 흥행 수익
4        북미 %
5         제작비
Name: 0, dtype: object

In [119]:
df_boxoffice.columns = df_boxoffice.iloc[0]
df_boxoffice

,순위,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
0,순위,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
1,1,아바타 (2009),"$2,847,246,203","$760,507,625",26.71%,"$237,000,000"
2,2,어벤저스: 엔드게임 (2019),"$2,797,501,328","$858,373,000",30.68%,"$356,000,000"
3,3,타이타닉 (1997),"$2,201,647,264","$659,363,944",29.95%,"$200,000,000"
4,4,스타 워즈: 깨어난 포스 (2015),"$2,068,223,624","$936,662,225",45.29%,"$245,000,000"
...,...,...,...,...,...,...
196,196,월드워 Z (2013),"$540,007,876","$202,359,711",37.47%,"$190,000,000"
197,197,메리다와 마법의 숲 (2012),"$538,983,207","$237,283,207",44.02%,"$185,000,000"
198,198,"심슨가족, 더 무비 (2007)","$536,414,270","$183,135,014",34.14%,"$75,000,000"
199,199,레버넌트: 죽음에서 돌아온 자 (2015),"$532,950,503","$183,637,894",34.46%,"$135,000,000"
200,200,메가로돈 (2018),"$530,243,742","$145,443,742",27.43%,"$130,000,000"

In [120]:
df_boxoffice.index = df_boxoffice['순위']
df_boxoffice

,순위,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
순위,,,,,,
순위,순위,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
1,1,아바타 (2009),"$2,847,246,203","$760,507,625",26.71%,"$237,000,000"
2,2,어벤저스: 엔드게임 (2019),"$2,797,501,328","$858,373,000",30.68%,"$356,000,000"
3,3,타이타닉 (1997),"$2,201,647,264","$659,363,944",29.95%,"$200,000,000"
4,4,스타 워즈: 깨어난 포스 (2015),"$2,068,223,624","$936,662,225",45.29%,"$245,000,000"
...,...,...,...,...,...,...
196,196,월드워 Z (2013),"$540,007,876","$202,359,711",37.47%,"$190,000,000"
197,197,메리다와 마법의 숲 (2012),"$538,983,207","$237,283,207",44.02%,"$185,000,000"
198,198,"심슨가족, 더 무비 (2007)","$536,414,270","$183,135,014",34.14%,"$75,000,000"
199,199,레버넌트: 죽음에서 돌아온 자 (2015),"$532,950,503","$183,637,894",34.46%,"$135,000,000"
200,200,메가로돈 (2018),"$530,243,742","$145,443,742",27.43%,"$130,000,000"

In [121]:
df_boxoffice.drop(columns=['순위'], inplace=True)

In [122]:
df_boxoffice

,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
순위,,,,,
순위,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
1,아바타 (2009),"$2,847,246,203","$760,507,625",26.71%,"$237,000,000"
2,어벤저스: 엔드게임 (2019),"$2,797,501,328","$858,373,000",30.68%,"$356,000,000"
3,타이타닉 (1997),"$2,201,647,264","$659,363,944",29.95%,"$200,000,000"
4,스타 워즈: 깨어난 포스 (2015),"$2,068,223,624","$936,662,225",45.29%,"$245,000,000"
...,...,...,...,...,...
196,월드워 Z (2013),"$540,007,876","$202,359,711",37.47%,"$190,000,000"
197,메리다와 마법의 숲 (2012),"$538,983,207","$237,283,207",44.02%,"$185,000,000"
198,"심슨가족, 더 무비 (2007)","$536,414,270","$183,135,014",34.14%,"$75,000,000"
199,레버넌트: 죽음에서 돌아온 자 (2015),"$532,950,503","$183,637,894",34.46%,"$135,000,000"
200,메가로돈 (2018),"$530,243,742","$145,443,742",27.43%,"$130,000,000"

In [123]:
df_boxoffice.iloc[0]

0
영화                영화
세계 흥행 수익    세계 흥행 수익
북미 흥행 수익    북미 흥행 수익
북미 %            북미 %
제작비              제작비
Name: 순위, dtype: object

In [124]:
df_boxoffice = df_boxoffice.drop(index='순위')

In [125]:
df_boxoffice

,영화,세계 흥행 수익,북미 흥행 수익,북미 %,제작비
순위,,,,,
1,아바타 (2009),"$2,847,246,203","$760,507,625",26.71%,"$237,000,000"
2,어벤저스: 엔드게임 (2019),"$2,797,501,328","$858,373,000",30.68%,"$356,000,000"
3,타이타닉 (1997),"$2,201,647,264","$659,363,944",29.95%,"$200,000,000"
4,스타 워즈: 깨어난 포스 (2015),"$2,068,223,624","$936,662,225",45.29%,"$245,000,000"
5,어벤저스: 인피니티 워 (2018),"$2,048,709,917","$678,815,482",33.13%,"$321,000,000"
...,...,...,...,...,...
196,월드워 Z (2013),"$540,007,876","$202,359,711",37.47%,"$190,000,000"
197,메리다와 마법의 숲 (2012),"$538,983,207","$237,283,207",44.02%,"$185,000,000"
198,"심슨가족, 더 무비 (2007)","$536,414,270","$183,135,014",34.14%,"$75,000,000"
199,레버넌트: 죽음에서 돌아온 자 (2015),"$532,950,503","$183,637,894",34.46%,"$135,000,000"
200,메가로돈 (2018),"$530,243,742","$145,443,742",27.43%,"$130,000,000"

영화 타이틀을 제목과 연도로 분리하기

In [126]:
import re
y = re.compile('\(\d+\)')
year = []
title = []

for i in df_boxoffice['영화']:
    m = y.search(i)
    g = m.group()
    title.append(i.replace(' '+g, ''))
    year.append(g.replace('(', '').replace(')', ''))
print(title)
print(year)

['아바타', '어벤저스: 엔드게임', '타이타닉', '스타 워즈: 깨어난 포스', '어벤저스: 인피니티 워', '스파이더맨: 노 웨이 홈', '쥬라기 월드', '라이온 킹', '어벤저스', '분노의 질주: 더 세븐', '겨울왕국 2', '어벤저스: 에이지 오브 울트론', '블랙 팬서', '해리 포터와 죽음의 성물 2', '스타 워즈: 라스트 제다이', '쥬라기 월드: 폴른 킹덤', '겨울왕국', '미녀와 야수', '인크레더블 2', '분노의 질주: 더 익스트림', '아이언맨 3', '미니언즈', '캡틴 아메리카: 시빌 워', '아쿠아맨', '반지의 제왕: 왕의 귀환', '스파이더맨: 파 프롬 홈', '캡틴 마블', '트랜스포머 3', '007 스카이폴', '트랜스포머: 사라진 시대', '다크 나이트 라이즈', '조커', '스타 워즈 에피소드 9: 라이즈 오브 스카이워커', '토이스토리 4', '토이스토리 3', '캐리비안의 해적: 망자의 함', '라이온 킹', '로그원: 스타 워즈 스토리', '알라딘', '캐리비안의 해적: 낯선 조류', '슈퍼배드 3', '쥬라기 공원', '도리를 찾아서', '스타 워즈 에피소드 1: 보이지 않는 위험', '이상한 나라의 앨리스', '주토피아', '해리 포터와 마법사의 돌', '호빗: 뜻밖의 여정', '다크 나이트', '해리 포터와 죽음의 성물 1', '슈퍼배드 2', '정글북', '쥬만지: 새로운 세계', '캐리비안의 해적: 세상의 끝', '호빗: 스마우그의 폐허', '호빗: 다섯 군대 전투', '반지의 제왕: 두 개의 탑', '해리 포터와 불사조 기사단', '니모를 찾아서', '해리 포터와 혼혈 왕자', '슈렉 2', '보헤미안 랩소디', '해리 포터와 불의 잔', '스파이더맨 3', '반지의 제왕: 반지 원정대', '아이스 에이지 3: 공룡시대', '007 스펙터', '스파이더맨: 홈커밍', '해리 포터와 비밀의 방', '아이스 에이지 4: 대륙 이동설', '마이펫의 이중생활', '배트맨 대 슈퍼맨: 저스티스의 시작', '늑대전사', '스타 워즈 에피소드 3: 시스의 복수', '헝거게임: 캣칭 파이어', '가디언즈 오브 갤럭시 Vol. 2', '인사이드 아웃', '베놈', '토르: 라그나로크', '트랜스포머: 패자의 역습', '인셉션', '브레이킹 던 Part 2', '스파이더맨', '원더 우먼', '인디펜던스 데이', '신비한 동물사전', '슈렉 3', '코코', '쥬만지: 넥스트 레벨', '해리 포터와 아즈카반의 죄수', '캐리비안의 해적: 죽은 자는 말이 없다', '이티', '2012', '미션 임파서블: 폴아웃', '인디아나 존스 4 - 크리스탈 해골의 왕국', '스파이더맨 2', '분노의 질주: 더 맥시멈', '데드풀 2', '데드풀', '스타 워즈 에피소드 4: 새로운 희망', '가디언즈 오브 갤럭시', '다빈치 코드', '분노의 질주: 홉스&쇼', '말레피센트', '어메이징 스파이더맨', '헝거게임: 모킹제이', '슈렉 포에버', '마다가스카 3: 이번엔 서커스다!', '수어사이드 스쿼드', '엑스맨: 데이즈 오브 퓨처 패스트', '나니아 연대기: 사자, 마녀, 그리고 옷장', '몬스터 대학교', '매트릭스 2 - 리로디드', '업', '나타지마동강세', '그래비티', '캡틴 아메리카: 윈터 솔저', '브레이킹 던 Part 1', '뉴문', '혹성탈출: 반격의 서막', '트랜스포머', '어메이징 스파이더맨 2', '그것', '토르: 러브 앤 썬더', '유랑지구', '이클립스', '미션 임파서블: 고스트 프로토콜', '헝거게임: 판엠의 불꽃', '모아나', '미션 임파서블: 로그네이션', '포레스트 검프', '닥터 스트레인지', '인터스텔라', '식스 센스', '007 노 타임 투 다이', '맨 오브 스틸', '아이스 에이지 2', '쿵푸팬더2', '헝거게임: 더 파이널', '저스티스 리그', '빅 히어로', '신비한 동물들과 그린델왈드의 범죄', '캐리비안의 해적: 블랙펄의 저주', '스타 워즈 에피소드 2: 클론의 습격', '토르: 다크월드', '씽', '몬스터 주식회사', '쿵푸팬더', '인크레더블', '마션', '핸콕', '분노의 질주: 언리미티드', '맨 인 블랙 3', '아이언맨 2', '라따뚜이', '앤트맨과 와스프', '드래곤 길들이기 2', '로건', '쥬라기 공원 2: 잃어버린 세계', '007 카지노 로얄', '패션 오브 크라이스트', '맘마미아!', '라이프 오브 파이', '트랜스포머: 최후의 기사', '마다가스카 2', '우주전쟁', '라푼젤', '007 퀀텀 오브 솔러스', '맨 인 블랙', '크루즈 패밀리', '행오버 2', '나는 전설이다', '아이언맨', '레디 플레이어 원', '오퍼레이션 레드 씨', '박물관이 살아있다!', '그레이의 50가지 그림자', '콩: 스컬 아일랜드', '개구쟁이 스머프', '킹콩', '카 2', '장화신은 고양이', '미인어', '아마겟돈', '투모로우', '19곰 테드', '스타 워즈 에피소드 5: 제국의 역습', '아메리칸 스나이퍼', '미션 임파서블 2', '차이나타운의 형사', '엑스맨: 아포칼립스', '셜록 홈즈: 그림자 게임', '슈퍼배드', '신데렐라', '마다가스카', '월드워 Z', '메리다와 마법의 숲', '심슨가족, 더 무비', '레버넌트: 죽음에서 돌아온 자', '메가로돈']
['2009', '2019', '1997', '2015', '2018', '2021', '2015', '2019', '2012', '2015', '2019', '2015', '2018', '2011', '2017', '2018', '2013', '2017', '2018', '2017', '2013', '2015', '2016', '2018', '2003', '2019', '2019', '2011', '2012', '2014', '2012', '2019', '2019', '2019', '2010', '2006', '1994', '2016', '2019', '2011', '2017', '1993', '2016', '1999', '2010', '2016', '2001', '2012', '2008', '2010', '2013', '2016', '2017', '2007', '2013', '2014', '2002', '2007', '2003', '2009', '2004', '2018', '2005', '2007', '2001', '2009', '2015', '2017', '2002', '2012', '2016', '2016', '2017', '2005', '2013', '2017', '2015', '2018', '2017', '2009', '2010', '2012', '2002', '2017', '1996', '2016', '2007', '2017', '2019', '2004', '2017', '1982', '2009', '2018', '2008', '2004', '2013', '2018', '2016', '1977', '2014', '2006', '2019', '2014', '2012', '2014', '2010', '2012', '2016', '2014', '2005', '2013', '2003', '2009', '2019', '2013', '2014', '2011', '2009', '2014', '2007', '2014', '2017', '2022', '2019', '2010', '2011', '2012', '2016', '2015', '1994', '2016', '2014', '1999', '2020', '2013', '2006', '2011', '2015', '2017', '2014', '2018', '2003', '2002', '2013', '2016', '2001', '2008', '2004', '2015', '2008', '2011', '2012', '2010', '2007', '2018', '2014', '2017', '1997', '2006', '2004', '2008', '2012', '2017', '2008', '2005', '2010', '2008', '1997', '2013', '2011', '2007', '2008', '2018', '2018', '2006', '2015', '2017', '2011', '2005', '2011', '2011', '2016', '1998', '2004', '2012', '1980', '2014', '2000', '2018', '2016', '2011', '2010', '2015', '2005', '2013', '2012', '2007', '2015', '2018']

In [127]:
df_boxoffice['MovieTitle'] = title
df_boxoffice['Year'] = year
df_boxoffice.drop(columns=['영화'], inplace=True)
df_boxoffice

,세계 흥행 수익,북미 흥행 수익,북미 %,제작비,MovieTitle,Year
순위,,,,,,
1,"$2,847,246,203","$760,507,625",26.71%,"$237,000,000",아바타,2009
2,"$2,797,501,328","$858,373,000",30.68%,"$356,000,000",어벤저스: 엔드게임,2019
3,"$2,201,647,264","$659,363,944",29.95%,"$200,000,000",타이타닉,1997
4,"$2,068,223,624","$936,662,225",45.29%,"$245,000,000",스타 워즈: 깨어난 포스,2015
5,"$2,048,709,917","$678,815,482",33.13%,"$321,000,000",어벤저스: 인피니티 워,2018
...,...,...,...,...,...,...
196,"$540,007,876","$202,359,711",37.47%,"$190,000,000",월드워 Z,2013
197,"$538,983,207","$237,283,207",44.02%,"$185,000,000",메리다와 마법의 숲,2012
198,"$536,414,270","$183,135,014",34.14%,"$75,000,000","심슨가족, 더 무비",2007
199,"$532,950,503","$183,637,894",34.46%,"$135,000,000",레버넌트: 죽음에서 돌아온 자,2015
200,"$530,243,742","$145,443,742",27.43%,"$130,000,000",메가로돈,2018

인덱스, 칼럼 명 영어로 바꾸기

In [128]:
df_boxoffice.index.name = 'rank'
df_boxoffice

,세계 흥행 수익,북미 흥행 수익,북미 %,제작비,MovieTitle,Year
rank,,,,,,
1,"$2,847,246,203","$760,507,625",26.71%,"$237,000,000",아바타,2009
2,"$2,797,501,328","$858,373,000",30.68%,"$356,000,000",어벤저스: 엔드게임,2019
3,"$2,201,647,264","$659,363,944",29.95%,"$200,000,000",타이타닉,1997
4,"$2,068,223,624","$936,662,225",45.29%,"$245,000,000",스타 워즈: 깨어난 포스,2015
5,"$2,048,709,917","$678,815,482",33.13%,"$321,000,000",어벤저스: 인피니티 워,2018
...,...,...,...,...,...,...
196,"$540,007,876","$202,359,711",37.47%,"$190,000,000",월드워 Z,2013
197,"$538,983,207","$237,283,207",44.02%,"$185,000,000",메리다와 마법의 숲,2012
198,"$536,414,270","$183,135,014",34.14%,"$75,000,000","심슨가족, 더 무비",2007
199,"$532,950,503","$183,637,894",34.46%,"$135,000,000",레버넌트: 죽음에서 돌아온 자,2015
200,"$530,243,742","$145,443,742",27.43%,"$130,000,000",메가로돈,2018

In [129]:
df_boxoffice.rename(columns={'세계 흥행 수익': 'WWBoxOffice', '북미 흥행 수익': 'DomesticBoxOffice',
                    '북미 %': 'DomesticPercentage', '제작비': 'Budget'}, inplace=True)
df_boxoffice

,WWBoxOffice,DomesticBoxOffice,DomesticPercentage,Budget,MovieTitle,Year
rank,,,,,,
1,"$2,847,246,203","$760,507,625",26.71%,"$237,000,000",아바타,2009
2,"$2,797,501,328","$858,373,000",30.68%,"$356,000,000",어벤저스: 엔드게임,2019
3,"$2,201,647,264","$659,363,944",29.95%,"$200,000,000",타이타닉,1997
4,"$2,068,223,624","$936,662,225",45.29%,"$245,000,000",스타 워즈: 깨어난 포스,2015
5,"$2,048,709,917","$678,815,482",33.13%,"$321,000,000",어벤저스: 인피니티 워,2018
...,...,...,...,...,...,...
196,"$540,007,876","$202,359,711",37.47%,"$190,000,000",월드워 Z,2013
197,"$538,983,207","$237,283,207",44.02%,"$185,000,000",메리다와 마법의 숲,2012
198,"$536,414,270","$183,135,014",34.14%,"$75,000,000","심슨가족, 더 무비",2007
199,"$532,950,503","$183,637,894",34.46%,"$135,000,000",레버넌트: 죽음에서 돌아온 자,2015
200,"$530,243,742","$145,443,742",27.43%,"$130,000,000",메가로돈,2018

In [130]:
df_boxoffice = df_boxoffice.reindex(
    ['MovieTitle', 'Year', 'WWBoxOffice', 'DomesticBoxOffice', 'DomesticPercentage', 'Budget'], axis=1)
df_boxoffice

,MovieTitle,Year,WWBoxOffice,DomesticBoxOffice,DomesticPercentage,Budget
rank,,,,,,
1,아바타,2009,"$2,847,246,203","$760,507,625",26.71%,"$237,000,000"
2,어벤저스: 엔드게임,2019,"$2,797,501,328","$858,373,000",30.68%,"$356,000,000"
3,타이타닉,1997,"$2,201,647,264","$659,363,944",29.95%,"$200,000,000"
4,스타 워즈: 깨어난 포스,2015,"$2,068,223,624","$936,662,225",45.29%,"$245,000,000"
5,어벤저스: 인피니티 워,2018,"$2,048,709,917","$678,815,482",33.13%,"$321,000,000"
...,...,...,...,...,...,...
196,월드워 Z,2013,"$540,007,876","$202,359,711",37.47%,"$190,000,000"
197,메리다와 마법의 숲,2012,"$538,983,207","$237,283,207",44.02%,"$185,000,000"
198,"심슨가족, 더 무비",2007,"$536,414,270","$183,135,014",34.14%,"$75,000,000"
199,레버넌트: 죽음에서 돌아온 자,2015,"$532,950,503","$183,637,894",34.46%,"$135,000,000"
200,메가로돈,2018,"$530,243,742","$145,443,742",27.43%,"$130,000,000"

타입을 int로

In [131]:
df_boxoffice['WWBoxOffice'] = df_boxoffice['WWBoxOffice'].str.replace(
    '$', '').str.replace(',', '').astype(int)
df_boxoffice['DomesticBoxOffice'] = df_boxoffice['DomesticBoxOffice'].str.replace(
    '$', '').str.replace(',', '').astype(int)
df_boxoffice['DomesticPercentage'] = df_boxoffice['DomesticPercentage'].str.replace(
    '%', '').astype(float)
df_boxoffice['Budget'] = df_boxoffice['Budget'].str.replace(
    '$', '').str.replace(',', '').astype(int)
df_boxoffice['Year'] = df_boxoffice['Year'].astype(int)

/tmp/ipykernel_91839/3976935458.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_boxoffice['WWBoxOffice'] = df_boxoffice['WWBoxOffice'].str.replace(
/tmp/ipykernel_91839/3976935458.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_boxoffice['DomesticBoxOffice'] = df_boxoffice['DomesticBoxOffice'].str.replace(
/tmp/ipykernel_91839/3976935458.py:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_boxoffice['Budget'] = df_boxoffice['Budget'].str.replace(

In [132]:
df_boxoffice.dtypes

0
MovieTitle             object
Year                    int64
WWBoxOffice             int64
DomesticBoxOffice       int64
DomesticPercentage    float64
Budget                  int64
dtype: object

In [133]:
df_boxoffice

,MovieTitle,Year,WWBoxOffice,DomesticBoxOffice,DomesticPercentage,Budget
rank,,,,,,
1,아바타,2009,2847246203,760507625,26.71,237000000
2,어벤저스: 엔드게임,2019,2797501328,858373000,30.68,356000000
3,타이타닉,1997,2201647264,659363944,29.95,200000000
4,스타 워즈: 깨어난 포스,2015,2068223624,936662225,45.29,245000000
5,어벤저스: 인피니티 워,2018,2048709917,678815482,33.13,321000000
...,...,...,...,...,...,...
196,월드워 Z,2013,540007876,202359711,37.47,190000000
197,메리다와 마법의 숲,2012,538983207,237283207,44.02,185000000
198,"심슨가족, 더 무비",2007,536414270,183135014,34.14,75000000
199,레버넌트: 죽음에서 돌아온 자,2015,532950503,183637894,34.46,135000000
200,메가로돈,2018,530243742,145443742,27.43,130000000

총합 구하기

In [134]:
df_boxoffice.loc['total'] = [
    'title',
    'year',
    df_boxoffice.WWBoxOffice.sum(),
    df_boxoffice.DomesticBoxOffice.sum(),
    round(df_boxoffice.DomesticPercentage.mean(), 2),
    df_boxoffice.Budget.sum()
]
df_boxoffice

,MovieTitle,Year,WWBoxOffice,DomesticBoxOffice,DomesticPercentage,Budget
rank,,,,,,
1,아바타,2009,2847246203,760507625,26.71,237000000
2,어벤저스: 엔드게임,2019,2797501328,858373000,30.68,356000000
3,타이타닉,1997,2201647264,659363944,29.95,200000000
4,스타 워즈: 깨어난 포스,2015,2068223624,936662225,45.29,245000000
5,어벤저스: 인피니티 워,2018,2048709917,678815482,33.13,321000000
...,...,...,...,...,...,...
197,메리다와 마법의 숲,2012,538983207,237283207,44.02,185000000
198,"심슨가족, 더 무비",2007,536414270,183135014,34.14,75000000
199,레버넌트: 죽음에서 돌아온 자,2015,532950503,183637894,34.46,135000000
200,메가로돈,2018,530243742,145443742,27.43,130000000
total,title,year,172451657762,60618933818,35.19,30130920000